### ISSUE TITLE
Cómo colaborar

### ISSUE THREAD

**Issue by a0viedo** [latamjs/organizacion#2]
Por otra parte, deberíamos juntar una serie de pasos de cómo colaborar con LatamJS. Algunos puntos que se me vienen a la mente:

- Aportar a que gane visibilidad
- Crear contenido técnico en español
- Recopilar contenido técnico (charlas, blog posts, tutoriales) en español

Ideas?

**Comment by eafelix** [comment]
Sumaria a la organizacion grupos de trabajo como estan definidos en iojs-es (un gran ejemplo a seguir)

**Comment by bevacqua** [comment]
+1000 a funcionar en WG

**Comment by eafelix** [comment]
ya creo el repo y defino los GT :P 
Hago un draft de los grupos y temas q va a tratar cada uno y sobre eso discutimos, les parece?
