### ISSUE TITLE
Temas a tratar

### ISSUE THREAD

**Issue by bevacqua** [latamjs/organizacion#3]
Qué temas creen que deberían discutirse en el grupo? Yo diría que habría que darle prioridad a eventos tanto pasados como futuros, ayudando a que la gente se motive a ir a algunos de estos eventos o incluso ayudarlos a que creen su propio evento. Imaginen algo como NodeSchool pero más generalizado a Meetups, por ejemplo.

Además de eventos también les gustaría que haya posts sobre programación en sí? Esto se me hace que debería estar en una sección un poco más relegada, y que debería darsele un poco más de importancia a eventos y novedades de la comunidad.

Qué opinan?

**Comment by gianu** [comment]
Opino igual, creo que hay que darle importancia a los diferentes eventos que hay en la comunidad latinoamericana y promover que la gente vaya y participe (ya sea dando una charla o solamente asistiendo).

Lo de la sección de post sobre programación creo que es algo que eventualmente podría funcionar, pero como decís creo que debería quedar relegada por ahora.

**Comment by eafelix** [comment]
Tal cual, todavia no definimos como va a ser el flujo del contenido y los grupos de trabajo
como para meternos con esos temas

**Comment by jeduan** [comment]
No se en los otros países, pero buscar patrocinadores para meetups y confs a veces es un lío y compartir experiencia en este aspecto podría ser muy valioso.

Aunque hay una cantidad fuerte de startups, la mayoría de ellas no están aun en un momento para dar dinero y nuestro plan ahora es juntar patrocinadores locales con otros globales que puedan hacer sentido (i.e. Github)
