### ISSUE TITLE
GT - ideas y definicion 

### ISSUE THREAD

**Issue by eafelix** [latamjs/organizacion#5]
La idea es poder definir las primeras tareas dentro de la comunidad para asi definir los primeros grupos de trabajo. 

Una pequeña propuesta como disparadora, a ver que opinan: 

-TRADUCCION 
  Equipos de traducción de artículos, contenido, charlas, etc 

-REVISION
 Equipos de revision para discutir cada traducción para estandarizar termino en la comunidad

-WEB 
 Desarrollo de la web, administración y mantenimiento.

-EVANGELIZACION 
Desarrollo de JS en la region, adopción de la tecnologia, promoción de projectos locales, etc

-MODERADORES 
Moderadores en la planeación de la información de toda la web, como los foros y blogs.

-COMUNIDADES EN LATAM 
Representantes de cada meetup que existe para poder compartir informacion de sus actividades. 

-GESTORES DE CONTENIDO 
Encargados de traer contenido a la web de gran relevancia (aca creo q seria algo en conjunto con la gente de la comunidad subiendo cosas entre todos)

-IMPULSADORES DE COMUNIDADES 
Encargados de fomentar mas comunidades a lo largo de Latinoamerica.

**Comment by mgtitimoli** [comment]
Me parece genial, podriamos reflejar estos equipos en canales en Slack, para que la gente se sume y cada equipo pueda empezar a empujar

**Comment by bevacqua** [comment]
Lo primero que deberíamos hacer es un hangout para definir bien los primeros #6

**Comment by cherta** [comment]
# Resumen

* **Moderadores:** A cargo de manejar y articular los canales públicos (salvo los específicos para cada grupo).
* **Eventos:** A cargo de prestar ayuda y difundir los eventos de la región.
* **Contenidos:** A cargo de generar, traducir y difundir contenidos en español.
* **Medios:** A cargo de administrar la presencia de **latam.js** en los diferentes medios.

## Moderadores

Tener un canal de slack abierto al público nos genera una gran responsabilidad, no podemos esperar que la comunidad lo administre, se comporte y lo desarrolle por si sola. 

Está en los cometidos de este GT hacer que cada persona que entra en nuestra comunidad tenga un lugar por donde empezar ya sea dirigiéndolo al canal de slack correcto, saludándolo o poniéndose a disposición.

## Eventos

Este GT deberá prestar ayuda para creación de eventos usando la experiencia generada en eventos anteriores. A su vez deberá dar a conocer los eventos que se lleven a cabo.

Nótese que la idea no es generar eventos (en una primera instancia) si no dar a conocer los existentes y dar apoyo a los que quieran hacerlo y no tengan las herramientas para ello.

## Contenidos

El GT de contenidos deberá trabajar en juntar y promover la creación de contenidos en español / portugués. 

Nótese que la idea no es generar contenido propio si bien ayudaría si no promover la creación del mismo y difundirlo a travez del sitio de **latam.js** y otros medios.

## Medios

Este GT es un poco transversal al resto de la organización ya que todo lo que hacemos no sirve si no lo publicamos en algún medio.

La tarea de este GT es administrar los medios que elijamos para la distribución de los contenidos generados ya sea twitter, facebook, sitio web, etc.

**Comment by bevacqua** [comment]
@cherta te agrego uno que no mencioné en el hangout pero es fundamental

## Web

Un GT encargado de todo lo que es el desarrollo del sitio web en sí mismo, lo cual implica tanto [latamjs.org](http://latamjs.org) como eventuales blogs, páginas de eventos, etc, inicialmente englobados en este GT.

**Comment by cherta** [comment]
@bevacqua lo pensé en medios. Por eso puse administrar. Era desde la web hasta las cta de social media pero rinde afuera. Como gusten :smile:

**Comment by bevacqua** [comment]
Claro pero yo veo "Medios" más bien como distribución o manejar las cuentas en redes sociales y no tanto el desarrollo de la web y afines

**Comment by ericdouglas** [comment]
Com conteúdos em português podem contar comigo! Irei ver os demais repositórios e voltar com sugestões!

Grande iniciativa! :smile:

**Comment by bevacqua** [comment]
Eric, that's the idea as well. Check out our slack for more info. You can get invited through [latamjs.org](http://latamjs.org)

**Comment by ericdouglas** [comment]
Ok @bevacqua !

**Comment by eafelix** [comment]
Si sobre los GT generales que armo @cherta definimos un listado de tareas de cada uno?
De esa forma queda mas claro para los que se sumen que tareas pueden realizar en cada GT y ademas tenemos claridad de la competencia de cada uno, como el caso de la web que comentaba @bevacqua .

**Comment by cherta** [comment]
Me gusta @eafelix. Yo creo que podríamos poner los grupos en un .md dentro del repo y asignar tareas con issues. Algo que funcione como action items y responsables.

Además pienso que tener los GT definidos en el sitio ayuda a que la gente se haga una idea mayor de lo que queremos lograr

**Comment by eafelix** [comment]
Dejo acá un draft sobre lo que propuso @cherta , a ver que opinan, sean libres de modificarlo y proponer, como puse anteriormente este tambien es un disparador de ideas: 

# Resumen

* **Comunidades:** A cargo de  informar, prestar ayuda y difundir las comunidades/eventos de la región.
* **Contenidos:** A cargo del desarrollo y administración de la web, como tambien generar, traducir y recopilar contenidos en español.
* **Medios:** A cargo de administrar la presencia de **latam.js** en los diferentes medios como promoción de eventos de cada comunidad y de cada generador de contenido.
* **Moderadores:** A cargo de manejar y articular los canales públicos (salvo los específicos para cada grupo).

## Comunidades - renombrado, previamente llamado "Eventos" 

Este GT deberá prestar ayuda para creación de comunidades/eventos usando la experiencia generada desde la mismas comunidades como tambien la fomentar la comunicación y camaradería entre ellas. 

- Punto de encuentro de las comunidades de Latam. 
- Facilitar la comunicación y difusión de todas las comunidades.
- Ayudar a crear nuevas comunidades 
- Dar conocer los eventos venideros 
- Crear vínculos mas estrechos entre las comunidades . 
- Promover y desarrollar.

## Contenidos

El GT de contenidos deberá trabajar en juntar y promover la creación de contenidos en español / portugués. 

- Desarrollo web ,entiéndase sites, blogs, foros, design, etc. 
- Administradores del site generado en el punto anterior. 
- Promotores de generación de contenido y de sus generadores actuales para darles un lugar mas donde puedan exponer sus artículos e ideas.
- Grupos traductores de contenidos relevantes en otros idiomas hacia español/portugués. 

Nótese que la idea no es solo generar contenido propio, si no promover ademas la creación del mismo y la promoción de los generadores de estos
La forma seria  difundirlo a travez del sitio de **latam.js** , comunidades y otros medios. 

## Medios

Este GT es  transversal al resto de la organización ya que todo lo que hacemos no sirve si no lo publicamos en algún medio. 
La tarea de este GT es administrar los medios que elijamos para la distribución de los contenidos generados ya sea twitter, facebook, sitio web, etc. 

- Promoción de las comunidades existentes y nuevas.
- Promoción de los nuevos contenidos creados. 
- Promoción de los eventos venideros.  

## Moderadores

Tener un canal de slack abierto al público nos genera una gran responsabilidad, no podemos esperar que la comunidad lo administre, se comporte y lo desarrolle por si sola. 

Está en los cometidos de este GT hacer que cada persona que entra en nuestra comunidad tenga un lugar por donde empezar ya sea dirigiéndolo al canal de slack correcto, saludándolo o poniéndose a disposición.

- Moderar los canales públicos.
- Suministrar ayuda a los nuevos miembros de la comunidad. 
- Velar por el respeto en la comunidad.

------------------------------------------------------------------------------------------------------------------------------------------

Se agregaron listas por cada punto para ir un poco a detalle el trabajo de cada GT. 
Como pueden ver los grupos de trabajo tienen mucha comunicación con **Medios**. 

Cada GT puede gestionarse de la forma que mas desee. Tambien es libre la forma en los GT organizan las tareas que involucran a otros GT. De ser posible si pueden crear una guia para que los nuevos integrantes puedan involucrarse y ayudar seria lo ideal (caso de iojs-es).

**Comment by bevacqua** [comment]
Insisto que la generación de contenidos debería ser separada de lo que es el desarrollo de la web, fuera de eso +1 a todo.

Con el tema de los moderadores estaría bueno que haya un cierto nivel de auto-moderación, es decir: tener un CoC y a medida que vayan surgiendo usuarios que frecuentemente se ofrezcan a ayudar voluntariamente a nuevos miembros ofrecerles la posibilidad de moderar el chat, obviamente siempre teniendo un oversight general del tema pero para no tener que invertir tantos recursos en esto

**Comment by eafelix** [comment]
+1 a la separación de contenidos con el desarrollo web. Obviamente van a trabajar muy codo a codo, pero esta bueno delimitar como vos decís, ámbitos de acción y decisión separados.

**Comment by cherta** [comment]
A ver si esta versión gusta más.

# Resumen

## GT Orgánicos

Los GT orgánicos son los que generan (o juntan) y producen el contenido. El mismo puede ser: posts, artículos, mini sitios o eventos.

El foco está sobre el **qué** más que en el **cómo**.

* **Comunidades:** A cargo de  informar, prestar ayuda y difundir las comunidades/eventos de la región.
* **Contenidos:** A cargo de generar, traducir y recopilar contenidos en español.

## GT De Soporte

Los GT de soporte son transversales a los primeros y brindan ejecución sobre los contenidos que estos desarrollan.

El foco está sobre el **cómo** más que en el **qué**.

* **Medios:** A cargo de administrar la presencia de **latam.js** en los diferentes medios como promoción de eventos de cada comunidad y de cada generador de contenido.
* **Web**: A cargo del desarrollo en si del sitio web y de otros sitios blogs, mini-sitos, etc de **latam.js**.

## Comunidades

Este GT deberá prestar ayuda para creación de comunidades / eventos usando la experiencia generada desde la mismas comunidades como también fomentar la comunicación y camaradería entre ellas.

- Punto de encuentro de las comunidades de Latam. 
- Facilitar la comunicación y difusión de todas las comunidades.
- Ayudar a crear nuevas comunidades.
- Dar conocer los eventos venideros.
- Crear vínculos mas estrechos entre las comunidades.
- Promover y desarrollar.

## Contenidos

El GT de contenidos deberá trabajar en juntar y promover la creación de contenidos en español / portugués. 

- Promotores de generación de contenido y de sus generadores actuales para darles un lugar mas donde puedan exponer sus artículos e ideas.
- Grupos traductores de contenidos relevantes en otros idiomas hacia español/portugués.

La idea de este GT no es sólo generar contenido propio, si no promover la creación del mismo y la promoción de los generadores de estos.

## Medios

La tarea de este GT es administrar los medios que elijamos para la distribución de los contenidos generados ya sea twitter, facebook, listas de distribuciíon etc. 

- Promoción de las comunidades existentes y nuevas.
- Promoción de los nuevos contenidos creados.
- Promoción de los eventos venideros.

Saqué moderadores porque me parece que más que un GT es una responsabilidad compartida entre los administradores de la comunidad. No sé si amerita hacerlo un GT o una responsabilidad compartida.

## Web

La tarea de este GT es implementar la página web de **latam.js** y otros sitios que la comunidad decida sacar y mantenerlos up to date.

- Desarrollar el sitio web principal de [latamjs.org](http://latamjs.org).
- Desarrollar dentro o fuera del sitio principal un sistema de blog (ala. HTML5Rocks! se habló) para publicar contenido.

### Reglas generales

Cada GT puede gestionarse de la forma que mas desee. Los mismos son libres de organizar sus tareas y las que involucran a otros GT. 

De ser posible se necesitará una guía para que los nuevos integrantes puedan involucrarse y ayudar (caso de iojs-es).

**Nota**: Quité **Moderadores** como GT porque me parece que más que un GT con una misión específica es una responsabilidad que cae sobre los administradores. No estoy diciendo que no tengamos que hacerla pero no me parece la dinámica que estamos buscando para un GT. Si habría que dejarlo escrito en algún lado.

**Comment by eafelix** [comment]
+1

**Comment by bevacqua** [comment]
Creados repos y channels de slack para cada WG.
