### ISSUE TITLE
Hangout

### ISSUE THREAD

**Issue by bevacqua** [latamjs/organizacion#6]
Qué días y fechas les quedan cómodos para un hangout?

Propongo mañana a las **3:00 PM UTC**:

- 12 AM AR
- 12 AM UY
- 12 AM BR
- 12 AM CL
- 11 AM BOL
- 10 AM PER
- 10 AM MEX
- 10 AM COL
- 9 AM CRC

Disculpen si me olvidé de algún país

**Comment by bevacqua** [comment]
Mi sugerencia de mañana es porque el viernes aparecemos en el JavaScript Weekly y estaría bueno tener estas cosas definidas para ese entonces

**Comment by gianu** [comment]
:+1:  esa hora me queda bien.

**Comment by cherta** [comment]
+1

**Comment by eafelix** [comment]
+1

**Comment by buritica** [comment]
@julianduque será mi representante, estoy en sesiones ejecutivas esta semana

**Comment by julianduque** [comment]
Lastimosamente estaré viajando a esa hora de regreso a Medellín pero @edsadr puede representar a Colombia sin problema

**Comment by edsadr** [comment]
ok representare a @julianduque y a @buritica por transitividad

**Comment by jeduan** [comment]
:+1:

**Comment by chitopolo** [comment]
+1 👍

Enviado desde mi iPhone

**Comment by pricco** [comment]
Me uno 12:20.

**Comment by bevacqua** [comment]
https://plus.google.com/hangouts/_/g6ryeiow2haevpgwadmxohocf4a

https://docs.google.com/document/d/1_7afUEzGwFMd9qMucCYgpBVgoqbUP3AF0WJiBcE0RmE/edit
