### ISSUE TITLE
Creacion del repo "Comunidades"

### ISSUE THREAD

**Issue by eafelix** [latamjs/organizacion#8]
Siguiendo la idea de estos issues: 

https://github.com/latamjs/eventos/issues/13 
https://github.com/latamjs/eventos/issues/13 

y la propuesta de tener Medios y Comunidades por separado cree el repositorio "Comunidades" para que este allí todo lo relacionado a ellas. 
Desde allí, su GT debería pedirle al GT Medios la notificación de sus eventos hacia la comunidad en los lugares donde crea mas óptimos.
Como esto no esta listo por ahora cada comunidad debería por si sola agregar sus nuevas fechas al repo "Eventos", siguiendo el mismo formato de este listado https://github.com/latamjs/eventos/blob/master/COMUNIDAD.md  

Por otro lado moveríamos este mismo archivo al repo "Comunidades" como README principal.
Que opinan?

**Comment by cherta** [comment]
@eafelix lo que decís era lo que yo me imaginaba. El GT medios recibe pedidos de los otros GT y los trabaja. Por eso lo de transversal que puse en el issue

**Comment by eafelix** [comment]
@cherta  jajajaa si si, tome tu idea :P
